version: '3.4'

services:

  ciceksepeti.basket.api:
   image: ${DOCKER_REGISTRY-}ciceksepetibasketapi
   build:
     context: .
     dockerfile: CicekSepeti.Basket.Api/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1

  redis:
    image: redis:alpine

  mongo:
    image: mongo

volumes:
    elasticsearch-data: